# Generated by Django 3.0 on 2019-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('vote_count', models.IntegerField(default=0)),
                ('views', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=300)),
            ],
        ),
    ]
